"""Opt-in isolated MySQL delivery tests. Never claim the shared worker queue."""
import os
from uuid import uuid4

import pytest


pytestmark = pytest.mark.skipif(os.getenv("RUN_MYSQL_TESTS") != "1", reason="requires project MySQL")


@pytest.fixture
def simulation_store():
    from sqlalchemy import delete, select
    from db.catalog_models import ManagedProduct, ProductAudit, ProductInspection, ProductRevision
    from db.job_models import InspectionJob, InspectionJobItem
    from db.models import AgentTrace, InspectionResult, InspectionTask
    from db.session import SessionLocal
    from services.simulation import DeliveryRequest, generate_preview

    request = DeliveryRequest(count=30, seed=19, batch_id="test-" + uuid4().hex, enqueue_inspection=False)
    product_ids = [x["product"]["product_id"] for x in generate_preview(request.model_dump(exclude={"enqueue_inspection"}))["products"]]
    with SessionLocal() as db:
        yield db, request
    # Resolve only the exact IDs generated by this fixture. No migrations/seeding,
    # broad queue cancellation, worker claim or unrelated record cleanup occurs.
    with SessionLocal() as db:
        ids = list(db.scalars(select(ManagedProduct.id).where(ManagedProduct.product_id.in_(product_ids))))
        job_ids = list(db.scalars(select(InspectionJobItem.job_id).where(InspectionJobItem.managed_product_id.in_(ids))))
        task_ids = list(db.scalars(select(InspectionTask.task_id).where(InspectionTask.product_id.in_(product_ids))))
        db.execute(delete(InspectionJobItem).where(InspectionJobItem.managed_product_id.in_(ids)))
        for job_id in set(job_ids):
            # Preserve any job that also contains records owned by someone else.
            if db.scalar(select(InspectionJobItem.id).where(InspectionJobItem.job_id == job_id).limit(1)) is None:
                db.execute(delete(InspectionJob).where(InspectionJob.id == job_id))
        for model in (ProductAudit, ProductInspection, ProductRevision):
            db.execute(delete(model).where(model.managed_product_id.in_(ids)))
        db.execute(delete(ManagedProduct).where(ManagedProduct.id.in_(ids)))
        for model in (AgentTrace, InspectionResult, InspectionTask):
            db.execute(delete(model).where(model.task_id.in_(task_ids)))
        db.commit()


def test_delivery_pending_history_and_idempotent_rules_job(simulation_store):
    from sqlalchemy import event, func, select
    from db.catalog_models import ManagedProduct, ProductAudit, ProductInspection, ProductRevision
    from db.job_models import InspectionJob, InspectionJobItem
    from services.simulation import deliver_batch

    db, request = simulation_store
    result = deliver_batch(db, request, "test:simulation")
    assert (result["created_count"], result["existing_count"], result["job_id"]) == (30, 0, None)
    ids = [p["id"] for p in result["products"]]
    products = db.scalars(select(ManagedProduct).where(ManagedProduct.id.in_(ids))).all()
    assert all(p.status == "pending" and p.version == 1 and p.latest_inspection_id is None for p in products)
    assert all(p.attributes["_simulation"]["source"] == "synthetic" for p in products)
    for model in (ProductRevision, ProductAudit):
        assert db.scalar(select(func.count()).select_from(model).where(model.managed_product_id.in_(ids))) == 30
    assert db.scalar(select(func.count()).select_from(ProductInspection).where(ProductInspection.managed_product_id.in_(ids))) == 0
    # Mark only this fixture's newly inserted job as cancellation-requested in
    # its INSERT transaction. A running shared worker can never claim it, even
    # in the interval between enqueue's commit and our explicit cancellation.
    def prevent_test_claim(_mapper, _connection, job):
        if job.actor == "test:simulation":
            job.cancel_requested = True

    event.listen(InspectionJob, "before_insert", prevent_test_claim)
    try:
        first = deliver_batch(db, request.model_copy(update={"enqueue_inspection": True}), "test:simulation")
    finally:
        event.remove(InspectionJob, "before_insert", prevent_test_claim)
    from services.jobs import cancel
    cancel(db, first["job_id"])
    repeated = deliver_batch(db, request.model_copy(update={"enqueue_inspection": True}), "test:simulation")
    assert first["job_id"] == repeated["job_id"]
    assert repeated["created_count"] == 0 and repeated["existing_count"] == 30
    assert repeated["products"] == result["products"]
    job = db.get(InspectionJob, first["job_id"])
    items = db.scalars(select(InspectionJobItem).where(InspectionJobItem.job_id == job.id)).all()
    assert job.mode == "rules" and len(items) == 30
    assert all(item.expected_version == 1 for item in items)


def test_changed_parameters_and_edited_product_conflict_without_overwrite(simulation_store):
    from sqlalchemy import select
    from app.catalog_schemas import ProductUpdate
    from db.catalog_models import ManagedProduct
    from services.catalog import CatalogError, get_product_detail, update_product
    from services.simulation import deliver_batch, generate_preview

    db, request = simulation_store
    first = deliver_batch(db, request, "test:simulation")
    for update in ({"scenario": "risky"}, {"count": 29}):
        with pytest.raises(CatalogError) as error:
            deliver_batch(db, request.model_copy(update=update), "test:simulation")
        assert error.value.status_code == 409
    first_id = first["products"][0]["id"]
    payload = generate_preview(request.model_dump(exclude={"enqueue_inspection"}))["products"][0]["product"]
    update_product(db, first_id, ProductUpdate(**{**payload, "title": payload["title"] + " 修改"}, expected_version=1), "test:editor")
    # Editing back to identical content is still a new version and must conflict.
    update_product(db, first_id, ProductUpdate(**payload, expected_version=2), "test:editor")
    with pytest.raises(CatalogError) as error:
        deliver_batch(db, request, "test:simulation")
    assert error.value.status_code == 409
    current = get_product_detail(db, first_id)
    assert current["version"] == 3 and len(current["revisions"]) == 3
    assert len(db.scalars(select(ManagedProduct).where(ManagedProduct.id.in_([x["id"] for x in first["products"]]))).all()) == 30


def test_concurrent_edit_after_create_commit_is_not_queued(simulation_store, monkeypatch):
    from app.catalog_schemas import ProductUpdate
    from db.job_models import InspectionJobItem
    from sqlalchemy import select
    from services import catalog
    from services.simulation import deliver_batch

    db, request = simulation_store
    original = catalog.create_product
    edited_ids = []

    def create_then_edit(session, payload, actor):
        created = original(session, payload, actor)
        edited_ids.append(created["id"])
        updated = catalog.update_product(session, created["id"], ProductUpdate(
            **{**payload.model_dump(), "title": payload.title + " 编辑内容"}, expected_version=1), "test:editor")
        return updated

    monkeypatch.setattr(catalog, "create_product", create_then_edit)
    with pytest.raises(catalog.CatalogError) as error:
        deliver_batch(db, request.model_copy(update={"enqueue_inspection": True}), "test:simulation")
    assert error.value.status_code == 409
    assert len(edited_ids) == 1
    current = catalog.get_product_detail(db, edited_ids[0])
    assert current["version"] == 2 and current["title"].endswith(" 编辑内容")
    assert db.scalar(select(InspectionJobItem.id).where(InspectionJobItem.managed_product_id == edited_ids[0])) is None


def test_api_auth_csrf_preview_and_delivery(simulation_store, monkeypatch):
    from fastapi import FastAPI
    from fastapi.testclient import TestClient
    from app.admin_auth import get_auth_settings, router as auth_router
    from app.simulation import router

    _, request = simulation_store
    monkeypatch.setenv("ADMIN_USERNAME", "simulation-test-admin")
    monkeypatch.setenv("ADMIN_PASSWORD", "simulation-test-password")
    monkeypatch.setenv("ADMIN_COOKIE_SECURE", "false")
    get_auth_settings.cache_clear()
    application = FastAPI()
    application.include_router(auth_router)
    application.include_router(router)
    try:
        with TestClient(application) as client:
            preview = request.model_dump(exclude={"enqueue_inspection"})
            for endpoint in ("preview", "deliver"):
                assert client.post(f"/api/admin/simulation/{endpoint}", json=preview).status_code == 401
            login = client.post("/api/admin/auth/login", json={"username": "simulation-test-admin", "password": "simulation-test-password"})
            assert login.status_code == 200
            try:
                for endpoint in ("preview", "deliver"):
                    assert client.post(f"/api/admin/simulation/{endpoint}", json=preview).status_code == 403
                client.headers["X-CSRF-Token"] = login.json()["csrf_token"]
                generated = client.post("/api/admin/simulation/preview", json=preview)
                assert generated.status_code == 200 and len(generated.json()["products"]) == 30
                delivered = client.post("/api/admin/simulation/deliver", json=request.model_dump())
                assert delivered.status_code == 200 and delivered.json()["created_count"] == 30
                assert client.post("/api/admin/simulation/deliver", json={**request.model_dump(), "scenario": "clean"}).status_code == 409
                assert client.post("/api/admin/simulation/preview", json={**preview, "count": 101}).status_code == 422
            finally:
                client.headers["X-CSRF-Token"] = login.json()["csrf_token"]
                client.post("/api/admin/auth/logout")
    finally:
        get_auth_settings.cache_clear()


def test_interrupted_delivery_resumes_without_duplicate_history(simulation_store, monkeypatch):
    from sqlalchemy import func, select
    from db.catalog_models import ProductAudit, ProductRevision
    from services import catalog
    from services.simulation import deliver_batch

    db, request = simulation_store
    original_create = catalog.create_product
    successful = 0

    def interrupt_after_three(*args, **kwargs):
        nonlocal successful
        if successful == 3:
            raise RuntimeError("controlled delivery interruption")
        result = original_create(*args, **kwargs)
        successful += 1
        return result

    with monkeypatch.context() as patch:
        patch.setattr(catalog, "create_product", interrupt_after_three)
        with pytest.raises(RuntimeError, match="controlled delivery interruption"):
            deliver_batch(db, request, "test:simulation")
    resumed = deliver_batch(db, request, "test:simulation")
    assert resumed["created_count"] == 27 and resumed["existing_count"] == 3
    ids = [x["id"] for x in resumed["products"]]
    for model in (ProductAudit, ProductRevision):
        assert db.scalar(select(func.count()).select_from(model).where(model.managed_product_id.in_(ids))) == 30


def test_concurrent_identical_delivery_reuses_products(simulation_store):
    from concurrent.futures import ThreadPoolExecutor
    from db.session import SessionLocal
    from services.simulation import deliver_batch

    _, request = simulation_store
    small_request = request.model_copy(update={"count": 6})

    def deliver(_index):
        with SessionLocal() as session:
            return deliver_batch(session, small_request, "test:simulation")

    with ThreadPoolExecutor(max_workers=2) as executor:
        results = list(executor.map(deliver, range(2)))
    assert results[0]["products"] == results[1]["products"]
    assert sum(result["created_count"] for result in results) == 6
    assert sum(result["existing_count"] for result in results) == 6
